### ISSUE TITLE
small error

### ISSUE THREAD

**Issue by i30817** [VR51/oneup#2]
https://github.com/VR51/oneup/blob/c0ad7580bc64f10c96680bc3699a4794e96fe159/oneup.sh#L259
https://github.com/VR51/oneup/blob/c0ad7580bc64f10c96680bc3699a4794e96fe159/oneup.sh#L267

I'm thinking you didn't want to write 'git git' in these  ;)

depth also requires a '--depth' (there are more of these than the 'git git')

**Comment by VR51** [comment]
That'll teach me to pay more attention. Thanks. Updated.
